/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TradingRouteImport } from './routes/trading'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RssDotxmlRouteImport } from './routes/rss[.]xml'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LatestRouteImport } from './routes/latest'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtomDotxmlRouteImport } from './routes/atom[.]xml'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CategoryRouteImport } from './routes/$category'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as CategoryIndexRouteImport } from './routes/$category.index'
import { Route as RssCategoryRouteImport } from './routes/rss.$category'
import { Route as NewsletterConfirmRouteImport } from './routes/newsletter.confirm'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthenticatedTagRulesRouteImport } from './routes/_authenticated/tag-rules'
import { Route as AuthenticatedSourcesRouteImport } from './routes/_authenticated/sources'
import { Route as AuthenticatedSopRouteImport } from './routes/_authenticated/sop'
import { Route as AuthenticatedSharePreviewRouteImport } from './routes/_authenticated/share-preview'
import { Route as AuthenticatedRunbookRouteImport } from './routes/_authenticated/runbook'
import { Route as AuthenticatedReviewRouteImport } from './routes/_authenticated/review'
import { Route as AuthenticatedPublishMonitorRouteImport } from './routes/_authenticated/publish-monitor'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedNewsdataRouteImport } from './routes/_authenticated/newsdata'
import { Route as AuthenticatedImportQueueRouteImport } from './routes/_authenticated/import-queue'
import { Route as AuthenticatedImageCleanRouteImport } from './routes/_authenticated/image-clean'
import { Route as AuthenticatedImageAuditRouteImport } from './routes/_authenticated/image-audit'
import { Route as AuthenticatedEmailMonitorRouteImport } from './routes/_authenticated/email-monitor'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfluenceRouteImport } from './routes/_authenticated/confluence'
import { Route as AuthenticatedBoardRouteImport } from './routes/_authenticated/board'
import { Route as AuthenticatedAuditLogRouteImport } from './routes/_authenticated/audit-log'
import { Route as AuthenticatedAtlassianSearchRouteImport } from './routes/_authenticated/atlassian-search'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as CategorySlugRouteImport } from './routes/$category.$slug'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicAuditDenialRouteImport } from './routes/api/public/audit-denial'
import { Route as ApiAdminTestLovableKeyRouteImport } from './routes/api/admin/test-lovable-key'
import { Route as AuthenticatedPreviewIdRouteImport } from './routes/_authenticated/preview.$id'
import { Route as AuthenticatedNewsdataSyncRouteImport } from './routes/_authenticated/newsdata.sync'
import { Route as AuthenticatedNewsdataSearchRouteImport } from './routes/_authenticated/newsdata.search'
import { Route as AuthenticatedNewsSearchRouteImport } from './routes/_authenticated/news.search'
import { Route as AuthenticatedNewsCreateRouteImport } from './routes/_authenticated/news.create'
import { Route as AuthenticatedBlogWriteRouteImport } from './routes/_authenticated/blog.write'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media.$'
import { Route as ApiPublicHooksRssIngestRouteImport } from './routes/api/public/hooks/rss-ingest'
import { Route as ApiPublicHooksNewsdataSyncRouteImport } from './routes/api/public/hooks/newsdata-sync'
import { Route as ApiPublicHooksNewsdataDailyRefreshRouteImport } from './routes/api/public/hooks/newsdata-daily-refresh'
import { Route as ApiPublicHooksGscSitemapRouteImport } from './routes/api/public/hooks/gsc-sitemap'
import { Route as ApiPublicHooksFbBulkPublishRouteImport } from './routes/api/public/hooks/fb-bulk-publish'
import { Route as ApiPublicHooksArticlePublishedRouteImport } from './routes/api/public/hooks/article-published'
import { Route as AuthenticatedNewsEditIdRouteImport } from './routes/_authenticated/news.edit.$id'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TradingRoute = TradingRouteImport.update({
  id: '/trading',
  path: '/trading',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RssDotxmlRoute = RssDotxmlRouteImport.update({
  id: '/rss.xml',
  path: '/rss.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LatestRoute = LatestRouteImport.update({
  id: '/latest',
  path: '/latest',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomDotxmlRoute = AtomDotxmlRouteImport.update({
  id: '/atom.xml',
  path: '/atom.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryRoute = CategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryIndexRoute = CategoryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CategoryRoute,
} as any)
const RssCategoryRoute = RssCategoryRouteImport.update({
  id: '/rss/$category',
  path: '/rss/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterConfirmRoute = NewsletterConfirmRouteImport.update({
  id: '/newsletter/confirm',
  path: '/newsletter/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTagRulesRoute = AuthenticatedTagRulesRouteImport.update({
  id: '/tag-rules',
  path: '/tag-rules',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSourcesRoute = AuthenticatedSourcesRouteImport.update({
  id: '/sources',
  path: '/sources',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSopRoute = AuthenticatedSopRouteImport.update({
  id: '/sop',
  path: '/sop',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSharePreviewRoute =
  AuthenticatedSharePreviewRouteImport.update({
    id: '/share-preview',
    path: '/share-preview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRunbookRoute = AuthenticatedRunbookRouteImport.update({
  id: '/runbook',
  path: '/runbook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReviewRoute = AuthenticatedReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublishMonitorRoute =
  AuthenticatedPublishMonitorRouteImport.update({
    id: '/publish-monitor',
    path: '/publish-monitor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsdataRoute = AuthenticatedNewsdataRouteImport.update({
  id: '/newsdata',
  path: '/newsdata',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImportQueueRoute =
  AuthenticatedImportQueueRouteImport.update({
    id: '/import-queue',
    path: '/import-queue',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImageCleanRoute = AuthenticatedImageCleanRouteImport.update({
  id: '/image-clean',
  path: '/image-clean',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImageAuditRoute = AuthenticatedImageAuditRouteImport.update({
  id: '/image-audit',
  path: '/image-audit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmailMonitorRoute =
  AuthenticatedEmailMonitorRouteImport.update({
    id: '/email-monitor',
    path: '/email-monitor',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfluenceRoute = AuthenticatedConfluenceRouteImport.update({
  id: '/confluence',
  path: '/confluence',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBoardRoute = AuthenticatedBoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAuditLogRoute = AuthenticatedAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAtlassianSearchRoute =
  AuthenticatedAtlassianSearchRouteImport.update({
    id: '/atlassian-search',
    path: '/atlassian-search',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CategoryRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuditDenialRoute = ApiPublicAuditDenialRouteImport.update({
  id: '/api/public/audit-denial',
  path: '/api/public/audit-denial',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTestLovableKeyRoute = ApiAdminTestLovableKeyRouteImport.update({
  id: '/api/admin/test-lovable-key',
  path: '/api/admin/test-lovable-key',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPreviewIdRoute = AuthenticatedPreviewIdRouteImport.update({
  id: '/preview/$id',
  path: '/preview/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsdataSyncRoute =
  AuthenticatedNewsdataSyncRouteImport.update({
    id: '/sync',
    path: '/sync',
    getParentRoute: () => AuthenticatedNewsdataRoute,
  } as any)
const AuthenticatedNewsdataSearchRoute =
  AuthenticatedNewsdataSearchRouteImport.update({
    id: '/search',
    path: '/search',
    getParentRoute: () => AuthenticatedNewsdataRoute,
  } as any)
const AuthenticatedNewsSearchRoute = AuthenticatedNewsSearchRouteImport.update({
  id: '/news/search',
  path: '/news/search',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewsCreateRoute = AuthenticatedNewsCreateRouteImport.update({
  id: '/news/create',
  path: '/news/create',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBlogWriteRoute = AuthenticatedBlogWriteRouteImport.update({
  id: '/blog/write',
  path: '/blog/write',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksRssIngestRoute = ApiPublicHooksRssIngestRouteImport.update({
  id: '/api/public/hooks/rss-ingest',
  path: '/api/public/hooks/rss-ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksNewsdataSyncRoute =
  ApiPublicHooksNewsdataSyncRouteImport.update({
    id: '/api/public/hooks/newsdata-sync',
    path: '/api/public/hooks/newsdata-sync',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksNewsdataDailyRefreshRoute =
  ApiPublicHooksNewsdataDailyRefreshRouteImport.update({
    id: '/api/public/hooks/newsdata-daily-refresh',
    path: '/api/public/hooks/newsdata-daily-refresh',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksGscSitemapRoute =
  ApiPublicHooksGscSitemapRouteImport.update({
    id: '/api/public/hooks/gsc-sitemap',
    path: '/api/public/hooks/gsc-sitemap',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFbBulkPublishRoute =
  ApiPublicHooksFbBulkPublishRouteImport.update({
    id: '/api/public/hooks/fb-bulk-publish',
    path: '/api/public/hooks/fb-bulk-publish',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksArticlePublishedRoute =
  ApiPublicHooksArticlePublishedRouteImport.update({
    id: '/api/public/hooks/article-published',
    path: '/api/public/hooks/article-published',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedNewsEditIdRoute = AuthenticatedNewsEditIdRouteImport.update({
  id: '/news/edit/$id',
  path: '/news/edit/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$category': typeof CategoryRouteWithChildren
  '/about': typeof AboutRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/latest': typeof LatestRoute
  '/mcp': typeof McpRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading': typeof TradingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atlassian-search': typeof AuthenticatedAtlassianSearchRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/board': typeof AuthenticatedBoardRoute
  '/confluence': typeof AuthenticatedConfluenceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-monitor': typeof AuthenticatedEmailMonitorRoute
  '/image-audit': typeof AuthenticatedImageAuditRoute
  '/image-clean': typeof AuthenticatedImageCleanRoute
  '/import-queue': typeof AuthenticatedImportQueueRoute
  '/newsdata': typeof AuthenticatedNewsdataRouteWithChildren
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/publish-monitor': typeof AuthenticatedPublishMonitorRoute
  '/review': typeof AuthenticatedReviewRoute
  '/runbook': typeof AuthenticatedRunbookRoute
  '/share-preview': typeof AuthenticatedSharePreviewRoute
  '/sop': typeof AuthenticatedSopRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/tag-rules': typeof AuthenticatedTagRulesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/rss/$category': typeof RssCategoryRoute
  '/$category/': typeof CategoryIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/blog/write': typeof AuthenticatedBlogWriteRoute
  '/news/create': typeof AuthenticatedNewsCreateRoute
  '/news/search': typeof AuthenticatedNewsSearchRoute
  '/newsdata/search': typeof AuthenticatedNewsdataSearchRoute
  '/newsdata/sync': typeof AuthenticatedNewsdataSyncRoute
  '/preview/$id': typeof AuthenticatedPreviewIdRoute
  '/api/admin/test-lovable-key': typeof ApiAdminTestLovableKeyRoute
  '/api/public/audit-denial': typeof ApiPublicAuditDenialRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/news/edit/$id': typeof AuthenticatedNewsEditIdRoute
  '/api/public/hooks/article-published': typeof ApiPublicHooksArticlePublishedRoute
  '/api/public/hooks/fb-bulk-publish': typeof ApiPublicHooksFbBulkPublishRoute
  '/api/public/hooks/gsc-sitemap': typeof ApiPublicHooksGscSitemapRoute
  '/api/public/hooks/newsdata-daily-refresh': typeof ApiPublicHooksNewsdataDailyRefreshRoute
  '/api/public/hooks/newsdata-sync': typeof ApiPublicHooksNewsdataSyncRoute
  '/api/public/hooks/rss-ingest': typeof ApiPublicHooksRssIngestRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/latest': typeof LatestRoute
  '/mcp': typeof McpRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading': typeof TradingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/atlassian-search': typeof AuthenticatedAtlassianSearchRoute
  '/audit-log': typeof AuthenticatedAuditLogRoute
  '/board': typeof AuthenticatedBoardRoute
  '/confluence': typeof AuthenticatedConfluenceRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/email-monitor': typeof AuthenticatedEmailMonitorRoute
  '/image-audit': typeof AuthenticatedImageAuditRoute
  '/image-clean': typeof AuthenticatedImageCleanRoute
  '/import-queue': typeof AuthenticatedImportQueueRoute
  '/newsdata': typeof AuthenticatedNewsdataRouteWithChildren
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/publish-monitor': typeof AuthenticatedPublishMonitorRoute
  '/review': typeof AuthenticatedReviewRoute
  '/runbook': typeof AuthenticatedRunbookRoute
  '/share-preview': typeof AuthenticatedSharePreviewRoute
  '/sop': typeof AuthenticatedSopRoute
  '/sources': typeof AuthenticatedSourcesRoute
  '/tag-rules': typeof AuthenticatedTagRulesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/rss/$category': typeof RssCategoryRoute
  '/$category': typeof CategoryIndexRoute
  '/blog': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/blog/write': typeof AuthenticatedBlogWriteRoute
  '/news/create': typeof AuthenticatedNewsCreateRoute
  '/news/search': typeof AuthenticatedNewsSearchRoute
  '/newsdata/search': typeof AuthenticatedNewsdataSearchRoute
  '/newsdata/sync': typeof AuthenticatedNewsdataSyncRoute
  '/preview/$id': typeof AuthenticatedPreviewIdRoute
  '/api/admin/test-lovable-key': typeof ApiAdminTestLovableKeyRoute
  '/api/public/audit-denial': typeof ApiPublicAuditDenialRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/news/edit/$id': typeof AuthenticatedNewsEditIdRoute
  '/api/public/hooks/article-published': typeof ApiPublicHooksArticlePublishedRoute
  '/api/public/hooks/fb-bulk-publish': typeof ApiPublicHooksFbBulkPublishRoute
  '/api/public/hooks/gsc-sitemap': typeof ApiPublicHooksGscSitemapRoute
  '/api/public/hooks/newsdata-daily-refresh': typeof ApiPublicHooksNewsdataDailyRefreshRoute
  '/api/public/hooks/newsdata-sync': typeof ApiPublicHooksNewsdataSyncRoute
  '/api/public/hooks/rss-ingest': typeof ApiPublicHooksRssIngestRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$category': typeof CategoryRouteWithChildren
  '/about': typeof AboutRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/auth': typeof AuthRoute
  '/connect': typeof ConnectRoute
  '/contact': typeof ContactRoute
  '/latest': typeof LatestRoute
  '/mcp': typeof McpRoute
  '/rss.xml': typeof RssDotxmlRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trading': typeof TradingRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/$category/$slug': typeof CategorySlugRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/atlassian-search': typeof AuthenticatedAtlassianSearchRoute
  '/_authenticated/audit-log': typeof AuthenticatedAuditLogRoute
  '/_authenticated/board': typeof AuthenticatedBoardRoute
  '/_authenticated/confluence': typeof AuthenticatedConfluenceRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/email-monitor': typeof AuthenticatedEmailMonitorRoute
  '/_authenticated/image-audit': typeof AuthenticatedImageAuditRoute
  '/_authenticated/image-clean': typeof AuthenticatedImageCleanRoute
  '/_authenticated/import-queue': typeof AuthenticatedImportQueueRoute
  '/_authenticated/newsdata': typeof AuthenticatedNewsdataRouteWithChildren
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/publish-monitor': typeof AuthenticatedPublishMonitorRoute
  '/_authenticated/review': typeof AuthenticatedReviewRoute
  '/_authenticated/runbook': typeof AuthenticatedRunbookRoute
  '/_authenticated/share-preview': typeof AuthenticatedSharePreviewRoute
  '/_authenticated/sop': typeof AuthenticatedSopRoute
  '/_authenticated/sources': typeof AuthenticatedSourcesRoute
  '/_authenticated/tag-rules': typeof AuthenticatedTagRulesRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/newsletter/confirm': typeof NewsletterConfirmRoute
  '/rss/$category': typeof RssCategoryRoute
  '/$category/': typeof CategoryIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/blog/write': typeof AuthenticatedBlogWriteRoute
  '/_authenticated/news/create': typeof AuthenticatedNewsCreateRoute
  '/_authenticated/news/search': typeof AuthenticatedNewsSearchRoute
  '/_authenticated/newsdata/search': typeof AuthenticatedNewsdataSearchRoute
  '/_authenticated/newsdata/sync': typeof AuthenticatedNewsdataSyncRoute
  '/_authenticated/preview/$id': typeof AuthenticatedPreviewIdRoute
  '/api/admin/test-lovable-key': typeof ApiAdminTestLovableKeyRoute
  '/api/public/audit-denial': typeof ApiPublicAuditDenialRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_authenticated/news/edit/$id': typeof AuthenticatedNewsEditIdRoute
  '/api/public/hooks/article-published': typeof ApiPublicHooksArticlePublishedRoute
  '/api/public/hooks/fb-bulk-publish': typeof ApiPublicHooksFbBulkPublishRoute
  '/api/public/hooks/gsc-sitemap': typeof ApiPublicHooksGscSitemapRoute
  '/api/public/hooks/newsdata-daily-refresh': typeof ApiPublicHooksNewsdataDailyRefreshRoute
  '/api/public/hooks/newsdata-sync': typeof ApiPublicHooksNewsdataSyncRoute
  '/api/public/hooks/rss-ingest': typeof ApiPublicHooksRssIngestRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$category'
    | '/about'
    | '/atom.xml'
    | '/auth'
    | '/connect'
    | '/contact'
    | '/latest'
    | '/mcp'
    | '/rss.xml'
    | '/search'
    | '/sitemap.xml'
    | '/trading'
    | '/unsubscribe'
    | '/$category/$slug'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/atlassian-search'
    | '/audit-log'
    | '/board'
    | '/confluence'
    | '/dashboard'
    | '/email-monitor'
    | '/image-audit'
    | '/image-clean'
    | '/import-queue'
    | '/newsdata'
    | '/pipeline'
    | '/publish-monitor'
    | '/review'
    | '/runbook'
    | '/share-preview'
    | '/sop'
    | '/sources'
    | '/tag-rules'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/newsletter/confirm'
    | '/rss/$category'
    | '/$category/'
    | '/blog/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/blog/write'
    | '/news/create'
    | '/news/search'
    | '/newsdata/search'
    | '/newsdata/sync'
    | '/preview/$id'
    | '/api/admin/test-lovable-key'
    | '/api/public/audit-denial'
    | '/api/public/contact'
    | '/api/public/health'
    | '/lovable/email/suppression'
    | '/news/edit/$id'
    | '/api/public/hooks/article-published'
    | '/api/public/hooks/fb-bulk-publish'
    | '/api/public/hooks/gsc-sitemap'
    | '/api/public/hooks/newsdata-daily-refresh'
    | '/api/public/hooks/newsdata-sync'
    | '/api/public/hooks/rss-ingest'
    | '/api/public/media/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/atom.xml'
    | '/auth'
    | '/connect'
    | '/contact'
    | '/latest'
    | '/mcp'
    | '/rss.xml'
    | '/search'
    | '/sitemap.xml'
    | '/trading'
    | '/unsubscribe'
    | '/$category/$slug'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/atlassian-search'
    | '/audit-log'
    | '/board'
    | '/confluence'
    | '/dashboard'
    | '/email-monitor'
    | '/image-audit'
    | '/image-clean'
    | '/import-queue'
    | '/newsdata'
    | '/pipeline'
    | '/publish-monitor'
    | '/review'
    | '/runbook'
    | '/share-preview'
    | '/sop'
    | '/sources'
    | '/tag-rules'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/newsletter/confirm'
    | '/rss/$category'
    | '/$category'
    | '/blog'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/blog/write'
    | '/news/create'
    | '/news/search'
    | '/newsdata/search'
    | '/newsdata/sync'
    | '/preview/$id'
    | '/api/admin/test-lovable-key'
    | '/api/public/audit-denial'
    | '/api/public/contact'
    | '/api/public/health'
    | '/lovable/email/suppression'
    | '/news/edit/$id'
    | '/api/public/hooks/article-published'
    | '/api/public/hooks/fb-bulk-publish'
    | '/api/public/hooks/gsc-sitemap'
    | '/api/public/hooks/newsdata-daily-refresh'
    | '/api/public/hooks/newsdata-sync'
    | '/api/public/hooks/rss-ingest'
    | '/api/public/media/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$category'
    | '/about'
    | '/atom.xml'
    | '/auth'
    | '/connect'
    | '/contact'
    | '/latest'
    | '/mcp'
    | '/rss.xml'
    | '/search'
    | '/sitemap.xml'
    | '/trading'
    | '/unsubscribe'
    | '/$category/$slug'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/atlassian-search'
    | '/_authenticated/audit-log'
    | '/_authenticated/board'
    | '/_authenticated/confluence'
    | '/_authenticated/dashboard'
    | '/_authenticated/email-monitor'
    | '/_authenticated/image-audit'
    | '/_authenticated/image-clean'
    | '/_authenticated/import-queue'
    | '/_authenticated/newsdata'
    | '/_authenticated/pipeline'
    | '/_authenticated/publish-monitor'
    | '/_authenticated/review'
    | '/_authenticated/runbook'
    | '/_authenticated/share-preview'
    | '/_authenticated/sop'
    | '/_authenticated/sources'
    | '/_authenticated/tag-rules'
    | '/blog/$slug'
    | '/email/unsubscribe'
    | '/newsletter/confirm'
    | '/rss/$category'
    | '/$category/'
    | '/blog/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/blog/write'
    | '/_authenticated/news/create'
    | '/_authenticated/news/search'
    | '/_authenticated/newsdata/search'
    | '/_authenticated/newsdata/sync'
    | '/_authenticated/preview/$id'
    | '/api/admin/test-lovable-key'
    | '/api/public/audit-denial'
    | '/api/public/contact'
    | '/api/public/health'
    | '/lovable/email/suppression'
    | '/_authenticated/news/edit/$id'
    | '/api/public/hooks/article-published'
    | '/api/public/hooks/fb-bulk-publish'
    | '/api/public/hooks/gsc-sitemap'
    | '/api/public/hooks/newsdata-daily-refresh'
    | '/api/public/hooks/newsdata-sync'
    | '/api/public/hooks/rss-ingest'
    | '/api/public/media/$'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CategoryRoute: typeof CategoryRouteWithChildren
  AboutRoute: typeof AboutRoute
  AtomDotxmlRoute: typeof AtomDotxmlRoute
  AuthRoute: typeof AuthRoute
  ConnectRoute: typeof ConnectRoute
  ContactRoute: typeof ContactRoute
  LatestRoute: typeof LatestRoute
  McpRoute: typeof McpRoute
  RssDotxmlRoute: typeof RssDotxmlRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TradingRoute: typeof TradingRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  BlogSlugRoute: typeof BlogSlugRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  NewsletterConfirmRoute: typeof NewsletterConfirmRoute
  RssCategoryRoute: typeof RssCategoryRoute
  BlogIndexRoute: typeof BlogIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiAdminTestLovableKeyRoute: typeof ApiAdminTestLovableKeyRoute
  ApiPublicAuditDenialRoute: typeof ApiPublicAuditDenialRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicHooksArticlePublishedRoute: typeof ApiPublicHooksArticlePublishedRoute
  ApiPublicHooksFbBulkPublishRoute: typeof ApiPublicHooksFbBulkPublishRoute
  ApiPublicHooksGscSitemapRoute: typeof ApiPublicHooksGscSitemapRoute
  ApiPublicHooksNewsdataDailyRefreshRoute: typeof ApiPublicHooksNewsdataDailyRefreshRoute
  ApiPublicHooksNewsdataSyncRoute: typeof ApiPublicHooksNewsdataSyncRoute
  ApiPublicHooksRssIngestRoute: typeof ApiPublicHooksRssIngestRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trading': {
      id: '/trading'
      path: '/trading'
      fullPath: '/trading'
      preLoaderRoute: typeof TradingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rss.xml': {
      id: '/rss.xml'
      path: '/rss.xml'
      fullPath: '/rss.xml'
      preLoaderRoute: typeof RssDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/latest': {
      id: '/latest'
      path: '/latest'
      fullPath: '/latest'
      preLoaderRoute: typeof LatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atom.xml': {
      id: '/atom.xml'
      path: '/atom.xml'
      fullPath: '/atom.xml'
      preLoaderRoute: typeof AtomDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category': {
      id: '/$category'
      path: '/$category'
      fullPath: '/$category'
      preLoaderRoute: typeof CategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/': {
      id: '/$category/'
      path: '/'
      fullPath: '/$category/'
      preLoaderRoute: typeof CategoryIndexRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/rss/$category': {
      id: '/rss/$category'
      path: '/rss/$category'
      fullPath: '/rss/$category'
      preLoaderRoute: typeof RssCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter/confirm': {
      id: '/newsletter/confirm'
      path: '/newsletter/confirm'
      fullPath: '/newsletter/confirm'
      preLoaderRoute: typeof NewsletterConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tag-rules': {
      id: '/_authenticated/tag-rules'
      path: '/tag-rules'
      fullPath: '/tag-rules'
      preLoaderRoute: typeof AuthenticatedTagRulesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sources': {
      id: '/_authenticated/sources'
      path: '/sources'
      fullPath: '/sources'
      preLoaderRoute: typeof AuthenticatedSourcesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sop': {
      id: '/_authenticated/sop'
      path: '/sop'
      fullPath: '/sop'
      preLoaderRoute: typeof AuthenticatedSopRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/share-preview': {
      id: '/_authenticated/share-preview'
      path: '/share-preview'
      fullPath: '/share-preview'
      preLoaderRoute: typeof AuthenticatedSharePreviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/runbook': {
      id: '/_authenticated/runbook'
      path: '/runbook'
      fullPath: '/runbook'
      preLoaderRoute: typeof AuthenticatedRunbookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/review': {
      id: '/_authenticated/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof AuthenticatedReviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publish-monitor': {
      id: '/_authenticated/publish-monitor'
      path: '/publish-monitor'
      fullPath: '/publish-monitor'
      preLoaderRoute: typeof AuthenticatedPublishMonitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/newsdata': {
      id: '/_authenticated/newsdata'
      path: '/newsdata'
      fullPath: '/newsdata'
      preLoaderRoute: typeof AuthenticatedNewsdataRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/import-queue': {
      id: '/_authenticated/import-queue'
      path: '/import-queue'
      fullPath: '/import-queue'
      preLoaderRoute: typeof AuthenticatedImportQueueRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/image-clean': {
      id: '/_authenticated/image-clean'
      path: '/image-clean'
      fullPath: '/image-clean'
      preLoaderRoute: typeof AuthenticatedImageCleanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/image-audit': {
      id: '/_authenticated/image-audit'
      path: '/image-audit'
      fullPath: '/image-audit'
      preLoaderRoute: typeof AuthenticatedImageAuditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/email-monitor': {
      id: '/_authenticated/email-monitor'
      path: '/email-monitor'
      fullPath: '/email-monitor'
      preLoaderRoute: typeof AuthenticatedEmailMonitorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/confluence': {
      id: '/_authenticated/confluence'
      path: '/confluence'
      fullPath: '/confluence'
      preLoaderRoute: typeof AuthenticatedConfluenceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/board': {
      id: '/_authenticated/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof AuthenticatedBoardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-log': {
      id: '/_authenticated/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuthenticatedAuditLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/atlassian-search': {
      id: '/_authenticated/atlassian-search'
      path: '/atlassian-search'
      fullPath: '/atlassian-search'
      preLoaderRoute: typeof AuthenticatedAtlassianSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$category/$slug': {
      id: '/$category/$slug'
      path: '/$slug'
      fullPath: '/$category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof CategoryRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/audit-denial': {
      id: '/api/public/audit-denial'
      path: '/api/public/audit-denial'
      fullPath: '/api/public/audit-denial'
      preLoaderRoute: typeof ApiPublicAuditDenialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/test-lovable-key': {
      id: '/api/admin/test-lovable-key'
      path: '/api/admin/test-lovable-key'
      fullPath: '/api/admin/test-lovable-key'
      preLoaderRoute: typeof ApiAdminTestLovableKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/preview/$id': {
      id: '/_authenticated/preview/$id'
      path: '/preview/$id'
      fullPath: '/preview/$id'
      preLoaderRoute: typeof AuthenticatedPreviewIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/newsdata/sync': {
      id: '/_authenticated/newsdata/sync'
      path: '/sync'
      fullPath: '/newsdata/sync'
      preLoaderRoute: typeof AuthenticatedNewsdataSyncRouteImport
      parentRoute: typeof AuthenticatedNewsdataRoute
    }
    '/_authenticated/newsdata/search': {
      id: '/_authenticated/newsdata/search'
      path: '/search'
      fullPath: '/newsdata/search'
      preLoaderRoute: typeof AuthenticatedNewsdataSearchRouteImport
      parentRoute: typeof AuthenticatedNewsdataRoute
    }
    '/_authenticated/news/search': {
      id: '/_authenticated/news/search'
      path: '/news/search'
      fullPath: '/news/search'
      preLoaderRoute: typeof AuthenticatedNewsSearchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/news/create': {
      id: '/_authenticated/news/create'
      path: '/news/create'
      fullPath: '/news/create'
      preLoaderRoute: typeof AuthenticatedNewsCreateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/blog/write': {
      id: '/_authenticated/blog/write'
      path: '/blog/write'
      fullPath: '/blog/write'
      preLoaderRoute: typeof AuthenticatedBlogWriteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/rss-ingest': {
      id: '/api/public/hooks/rss-ingest'
      path: '/api/public/hooks/rss-ingest'
      fullPath: '/api/public/hooks/rss-ingest'
      preLoaderRoute: typeof ApiPublicHooksRssIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/newsdata-sync': {
      id: '/api/public/hooks/newsdata-sync'
      path: '/api/public/hooks/newsdata-sync'
      fullPath: '/api/public/hooks/newsdata-sync'
      preLoaderRoute: typeof ApiPublicHooksNewsdataSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/newsdata-daily-refresh': {
      id: '/api/public/hooks/newsdata-daily-refresh'
      path: '/api/public/hooks/newsdata-daily-refresh'
      fullPath: '/api/public/hooks/newsdata-daily-refresh'
      preLoaderRoute: typeof ApiPublicHooksNewsdataDailyRefreshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/gsc-sitemap': {
      id: '/api/public/hooks/gsc-sitemap'
      path: '/api/public/hooks/gsc-sitemap'
      fullPath: '/api/public/hooks/gsc-sitemap'
      preLoaderRoute: typeof ApiPublicHooksGscSitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/fb-bulk-publish': {
      id: '/api/public/hooks/fb-bulk-publish'
      path: '/api/public/hooks/fb-bulk-publish'
      fullPath: '/api/public/hooks/fb-bulk-publish'
      preLoaderRoute: typeof ApiPublicHooksFbBulkPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/article-published': {
      id: '/api/public/hooks/article-published'
      path: '/api/public/hooks/article-published'
      fullPath: '/api/public/hooks/article-published'
      preLoaderRoute: typeof ApiPublicHooksArticlePublishedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/news/edit/$id': {
      id: '/_authenticated/news/edit/$id'
      path: '/news/edit/$id'
      fullPath: '/news/edit/$id'
      preLoaderRoute: typeof AuthenticatedNewsEditIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedNewsdataRouteChildren {
  AuthenticatedNewsdataSearchRoute: typeof AuthenticatedNewsdataSearchRoute
  AuthenticatedNewsdataSyncRoute: typeof AuthenticatedNewsdataSyncRoute
}

const AuthenticatedNewsdataRouteChildren: AuthenticatedNewsdataRouteChildren = {
  AuthenticatedNewsdataSearchRoute: AuthenticatedNewsdataSearchRoute,
  AuthenticatedNewsdataSyncRoute: AuthenticatedNewsdataSyncRoute,
}

const AuthenticatedNewsdataRouteWithChildren =
  AuthenticatedNewsdataRoute._addFileChildren(
    AuthenticatedNewsdataRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAtlassianSearchRoute: typeof AuthenticatedAtlassianSearchRoute
  AuthenticatedAuditLogRoute: typeof AuthenticatedAuditLogRoute
  AuthenticatedBoardRoute: typeof AuthenticatedBoardRoute
  AuthenticatedConfluenceRoute: typeof AuthenticatedConfluenceRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmailMonitorRoute: typeof AuthenticatedEmailMonitorRoute
  AuthenticatedImageAuditRoute: typeof AuthenticatedImageAuditRoute
  AuthenticatedImageCleanRoute: typeof AuthenticatedImageCleanRoute
  AuthenticatedImportQueueRoute: typeof AuthenticatedImportQueueRoute
  AuthenticatedNewsdataRoute: typeof AuthenticatedNewsdataRouteWithChildren
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedPublishMonitorRoute: typeof AuthenticatedPublishMonitorRoute
  AuthenticatedReviewRoute: typeof AuthenticatedReviewRoute
  AuthenticatedRunbookRoute: typeof AuthenticatedRunbookRoute
  AuthenticatedSharePreviewRoute: typeof AuthenticatedSharePreviewRoute
  AuthenticatedSopRoute: typeof AuthenticatedSopRoute
  AuthenticatedSourcesRoute: typeof AuthenticatedSourcesRoute
  AuthenticatedTagRulesRoute: typeof AuthenticatedTagRulesRoute
  AuthenticatedBlogWriteRoute: typeof AuthenticatedBlogWriteRoute
  AuthenticatedNewsCreateRoute: typeof AuthenticatedNewsCreateRoute
  AuthenticatedNewsSearchRoute: typeof AuthenticatedNewsSearchRoute
  AuthenticatedPreviewIdRoute: typeof AuthenticatedPreviewIdRoute
  AuthenticatedNewsEditIdRoute: typeof AuthenticatedNewsEditIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAtlassianSearchRoute: AuthenticatedAtlassianSearchRoute,
  AuthenticatedAuditLogRoute: AuthenticatedAuditLogRoute,
  AuthenticatedBoardRoute: AuthenticatedBoardRoute,
  AuthenticatedConfluenceRoute: AuthenticatedConfluenceRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmailMonitorRoute: AuthenticatedEmailMonitorRoute,
  AuthenticatedImageAuditRoute: AuthenticatedImageAuditRoute,
  AuthenticatedImageCleanRoute: AuthenticatedImageCleanRoute,
  AuthenticatedImportQueueRoute: AuthenticatedImportQueueRoute,
  AuthenticatedNewsdataRoute: AuthenticatedNewsdataRouteWithChildren,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedPublishMonitorRoute: AuthenticatedPublishMonitorRoute,
  AuthenticatedReviewRoute: AuthenticatedReviewRoute,
  AuthenticatedRunbookRoute: AuthenticatedRunbookRoute,
  AuthenticatedSharePreviewRoute: AuthenticatedSharePreviewRoute,
  AuthenticatedSopRoute: AuthenticatedSopRoute,
  AuthenticatedSourcesRoute: AuthenticatedSourcesRoute,
  AuthenticatedTagRulesRoute: AuthenticatedTagRulesRoute,
  AuthenticatedBlogWriteRoute: AuthenticatedBlogWriteRoute,
  AuthenticatedNewsCreateRoute: AuthenticatedNewsCreateRoute,
  AuthenticatedNewsSearchRoute: AuthenticatedNewsSearchRoute,
  AuthenticatedPreviewIdRoute: AuthenticatedPreviewIdRoute,
  AuthenticatedNewsEditIdRoute: AuthenticatedNewsEditIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CategoryRouteChildren {
  CategorySlugRoute: typeof CategorySlugRoute
  CategoryIndexRoute: typeof CategoryIndexRoute
}

const CategoryRouteChildren: CategoryRouteChildren = {
  CategorySlugRoute: CategorySlugRoute,
  CategoryIndexRoute: CategoryIndexRoute,
}

const CategoryRouteWithChildren = CategoryRoute._addFileChildren(
  CategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CategoryRoute: CategoryRouteWithChildren,
  AboutRoute: AboutRoute,
  AtomDotxmlRoute: AtomDotxmlRoute,
  AuthRoute: AuthRoute,
  ConnectRoute: ConnectRoute,
  ContactRoute: ContactRoute,
  LatestRoute: LatestRoute,
  McpRoute: McpRoute,
  RssDotxmlRoute: RssDotxmlRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TradingRoute: TradingRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  BlogSlugRoute: BlogSlugRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  NewsletterConfirmRoute: NewsletterConfirmRoute,
  RssCategoryRoute: RssCategoryRoute,
  BlogIndexRoute: BlogIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiAdminTestLovableKeyRoute: ApiAdminTestLovableKeyRoute,
  ApiPublicAuditDenialRoute: ApiPublicAuditDenialRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicHooksArticlePublishedRoute: ApiPublicHooksArticlePublishedRoute,
  ApiPublicHooksFbBulkPublishRoute: ApiPublicHooksFbBulkPublishRoute,
  ApiPublicHooksGscSitemapRoute: ApiPublicHooksGscSitemapRoute,
  ApiPublicHooksNewsdataDailyRefreshRoute:
    ApiPublicHooksNewsdataDailyRefreshRoute,
  ApiPublicHooksNewsdataSyncRoute: ApiPublicHooksNewsdataSyncRoute,
  ApiPublicHooksRssIngestRoute: ApiPublicHooksRssIngestRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
